# Ansible Inventory for Taminator Build

[rocky_build]
rocky ansible_host=192.168.122.100 ansible_user=testuser ansible_python_interpreter=/usr/bin/python3

[rocky_build:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'

